### ISSUE TITLE
Any way to save the interactive dot plot?

### ISSUE THREAD

**Issue by Jennie17** [MariaNattestad/Assemblytics#10]
Hi,

Thanks for developing such a nice tool. User-friendly as well.

The interactive dot plot is great, just wondering is there anyway to save it as a figure with proper resolution (say 300dpi or higher) for publication?

The code page has explained that "interactive dot plot which is only available in the web version".

**Comment by MariaNattestad** [comment]
Thank you! I'm glad you found Assemblytics useful.
Since you want to have a high-res image for publication, I recommend saving the dot plot as an SVG file, which is the format it is created in already, which is a vector format so it has infinite resolution. 
There are a few ways to save SVGs from websites. 

There's a Chrome extension you can try: https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp?hl=en-GB

And here is an alternative:
https://nytimes.github.io/svg-crowbar/

After you save the SVG, you can submit it straight to the journal, or you can even open it in Illustrator or Inkscape (free) to edit it.
