### ISSUE TITLE
Inversions and Translocations

### ISSUE THREAD

**Issue by kmogroethe** [MariaNattestad/Assemblytics#12]
Hi Maria, 

I noticed in the between alignment perl script that Assemblytics ignores inversions and interchromosomal events (or at least it looks like it identifies them, but declines to consider them for the final file). Is there a reason why this is?

Thanks!

**Comment by MariaNattestad** [comment]
Hi Kara

Yes, I decided not to include those calls because I didn't trust the ability to call them accurately or meaningfully from an assembly. With too few inversions and translocations to properly check the assembly-based method's ability to call them, and with the threat of repeat-based misassemblies, we decided not to report these variant calls. They are still in that script because we initially looked at them but now have them just filtered out of the final results, but we didn't want to report them and have anyone trusting that they are necessarily true.

Maria

**Comment by kmogroethe** [comment]
Ah I see. So if I follow, the issue was false positives in the final dataset? 

The reason why I'm asking is that I am trying to come up with a SV identification pipeline for small (23 Mbp) genomes for which I have PacBio reads + assemblies. I also have a set of known structural variants which I'm using to guide some of my decisions. My idea was to include SVs that are supported by both assembly data (through Assemblytics) and by the raw reads (using Sniffles). After tweaking the Assemblytics scripts to give me inversions, either data set by itself definitely results in some false positives, but if I look at the inversions that are present in both data sets I'm able to identify all inversions that are present in my known SV dataset (with all inversions I suspect to be false positives removed).

**Comment by MariaNattestad** [comment]
That's a great use case for taking those inversions and translocations from Assemblytics and making use of them. At the time I made Assemblytics, Fritz had not built Sniffles yet, so we couldn't verify whether our inversion result were false positives or not--we simply weren't confident either way.
