### ISSUE TITLE
Does it have to be a delta file

### ISSUE THREAD

**Issue by peflanag** [MariaNattestad/Assemblytics#15]
Does Assemblytics have to be in a delta format? I am having issues making delta files with MUMmer 3 and MUMmer 4 and will attache screenshots below. I obnly happened along Assemblytics yesterday and before hand I was making BAM files to import into Tablet to view deletions and also vcf files using sniffles. I really want to use Assemblytics but cannot seem to make .delta files.

I am very new to command line and a novice. My background is microbiology.

Cheers

Peter

MUMmer 3 screenshot
<img width="606" alt="screenshot 2018-12-20 at 09 29 03" src="https://user-images.githubusercontent.com/32863969/50284670-ae05f980-0451-11e9-94bd-1cd5e16bd192.png">

MUMmer 4 screenshot
<img width="392" alt="screenshot 2018-12-20 at 11 49 22" src="https://user-images.githubusercontent.com/32863969/50284684-b9592500-0451-11e9-8f65-42dbad054f24.png">

**Comment by MariaNattestad** [comment]
Assemblytics does only work with delta files.
If you are aligning a genome assembly to a reference genome, then MUMmer + Assemblytics is the right choice for variant-calling. If you are instead aligning long reads directly (without first assembling them) then NGM-LR/Minimap2 + Sniffles is the right choice for variant-calling. Sniffles should not be used on assemblies, and Assemblytics should not be used on raw reads.
If you do have an assembly and want to go with MUMmer, then I think you're close, but you just have to try a few more things to run MUMmer correctly. Did you check what the manual says about supported file formats? If you need more help running MUMmer and reading the manual is not helping, then I recommend posting on Biostars: https://www.biostars.org/
You will also probably want to use the web version of Assemblytics at assemblytics.com, since it is very user-friendly.
Best of luck!

**Comment by peflanag** [comment]
So I used porechop to trim my Oxford Nanopore basecalled reads then used NGMLR to align with a reference sequence and got a fasta output. Then I tried to run this through Assemblytics. Should I instead use BWA and then run it through Assemblytics? I’d rather use Assemblytics for the visual representation as uppose to sniffles which just gives me a vcf output. 

Cheers

**Comment by MariaNattestad** [comment]
Assemblytics is for assemblies only, so it's not a good fit for your analysis, sorry!
NGMLR+Sniffles is the right thing to do, so I would recommend looking at visualization after the Sniffles step. Again, Biostars would be a good place to ask for recommendations about visualizing your VCF file.
