### ISSUE TITLE
PDFs do not open

### ISSUE THREAD

**Issue by JohnUrban** [MariaNattestad/Assemblytics#2]
Hi,

Thanks for the great tool.

I cloned the source code onto a Mac OS X:

```
git clone https://github.com/MariaNattestad/Assemblytics.git
```

When I run the Assemblytics pipeline, everything goes smoothly/successfully -- but I cannot open most of the PDFs. "Preview" says about the file(s), "It may be damaged or use a file format that Preview doesn't recognize."

Any help/advice would be appreciated - and apologies if this is something obvious.

Many thanks,
John

p.s. here is the error log
DELTAFILTER,DONE,Step 1: delta-filter completed successfully
UNIQFILTER,DONE,Step 2: Assemblytics_uniq_len_filter.py completed successfully
BETWEEN,DONE,Step 3: Assemblytics_between_alignments.pl completed successfully
WITHIN,DONE,Step 4: Assemblytics_within_alignment.py completed successfully
COMBINE,DONE,Step 5: Variants combined successfully
SUMMARY,DONE,Step 7: Assemblytics_summary.py completed successfully

**Comment by MariaNattestad** [comment]
Thank you for pointing this out. It looks like that happens when there are no variants in that size range, so R won't create a .png file when there is nothing to plot, but it creates an unreadable .pdf file. I have fixed it now, so it doesn't create those files anymore. Let me know if the problem persists, or if there are .png files with no matching .pdf files. 

Thanks!
Maria

**Comment by JohnUrban** [comment]
Seems to be all better now.
Thanks! 
(closing issue)
