### ISSUE TITLE
cat fail

### ISSUE THREAD

**Issue by JohnUrban** [MariaNattestad/Assemblytics#3]
Hi again,

I'm running assemblytics on a fake "bad" assembly of the E. coli genome. Basically, the e. coli genome is chopped up into 10 blocks with some sequence trimmed off to each side of each block. Then every other (even numbered) blocks are reverse complemented before stitching the blocks back in order with NNNNNN in between each (as if scaffolded poorly). So:
1 --- 2 --- 3 --- 4 --- 5 --- 6 --- 7 --- 8 --- 9 --- 10
becomes
1 --- 2' --- 3 --- 4' --- 5 --- 6' --- 7 --- 8' --- 9 --- 10'
where N' means the rev comp of what it should be.

When I run assemblytics, this happens:

```
Input delta file: OUT.l10000.delta
Output prefix: 00-concat-assemblytic
Unique anchor length: 10000
Path to R scripts: /Users/johnurban/searchPaths/software/assemblytics/0.0/
1. Filter delta file
First read through the file: 0 seconds for 1 query-reference combinations
Filtering alignments of 1 queries
Progress: 100%
Progress: 100%
Deciding which alignments to keep: 0 seconds for 1 queries
Reading file and recording all the entries we decided to keep: 0 seconds for 21 total lines in file
2. Finding variants between alignments
Loaded 10 alignments
3. Finding variants within alignments
4. Combine variants between and within alignments
Check 00-concat-assemblytic.progress.log for errors.
```

00-concat-assemblytic.progress.log 

```
00-concat-assemblytic
DELTAFILTER,DONE,Step 1: delta-filter completed successfully
UNIQFILTER,DONE,Step 2: Assemblytics_uniq_len_filter.py completed successfully
BETWEEN,DONE,Step 3: Assemblytics_between_alignments.pl completed successfully
WITHIN,DONE,Step 4: Assemblytics_within_alignment.py completed successfully
COMBINE,FAIL,Step 5: cat failed
```

I was hoping it would get up to the dotplot.

Can you explain to me what this means, whats happening, etc?

many thanks,

John

**Comment by MariaNattestad** [comment]
The pipeline requires there to be variants before creating any plots, which is an old requirement from when there was nothing to plot if there were no variants. I have removed this requirement now so you can at least see the dot plots. Assemblytics does not try to detect inversions, by the way, but only insertions and deletions as well as tandem and other repeat expansions and contractions. 
Assemblytics is not made for detecting problems with assemblies, but for calling biological variants from the parts of the assembly that robustly align uniquely to the reference. 

Also note that I don't recommend using scaffolded genomes since there will be false positives when the number of Ns doesn't exactly match the distance between the scaffolded contigs in the reference genome. There is a note about this in the README, and I would make Assemblytics validate inputs to prevent this, but it is not possible for Assemblytics to detect scaffolding from the delta file alone.

**Comment by JohnUrban** [comment]
Thanks for the quick response.
