### ISSUE TITLE
Identification of tandem duplications

### ISSUE THREAD

**Issue by MehmetGoktay** [MariaNattestad/Assemblytics#34]
Hi Maria,

thanks for this wonderful tool.

I was just wondering , would it be possible to interpret tandem expensions as tandem duplications?

Because basically it should look like an insertion event in query sequence between alignments.

Best Regards,
Mehmet

**Comment by MariaNattestad** [comment]
Yes a tandem duplication would fall under the category of a tandem expansion. I used "tandem expansion" because it is more general. Since the delta file uploaded to Assemblytics doesn't actually contain the base sequences, Assemblytics doesn't have the power to analyze the repeat structure directly. In the [paper](https://www.biorxiv.org/content/10.1101/044925v1.full.pdf) in figure 1A, the diagram for "tandem expansion" includes some sequence in the middle, which could be an insertion of new sequence in between the duplicated sequence. In that kind of example, calling it a tandem duplication might oversimplify it a bit, so I went with a more general term to encompass those cases as well.
