### ISSUE TITLE
No file uploaded

### ISSUE THREAD

**Issue by weiluwl** [MariaNattestad/Assemblytics#49]
Hi,

I think the server is filled again. I keep getting the error no file uploaded.

Thanks,
Wei

**Comment by mschatz** [comment]
Cleaning up now!

**Comment by Daeap** [comment]
Hi, just wanted to say the same is happening again right now. 

Thank you for your time,

David

**Comment by matt-shenton** [comment]
HI there,

many thanks for the assemblytics tool.

I'm also having file upload trouble.

Best wishes

Matt Shenton

**Comment by robackem** [comment]
Hello, just wanted to make a note that this is happening again.

Many thanks!

**Comment by mschatz** [comment]
Please try again. It should be fixed now!

Mike

**Comment by ethan-baldwin** [comment]
Hi, it seems like the server is filled up again. Thanks!

**Comment by Gon1976** [comment]
Hi Mike,
could be web server full? I have the error "no file upload"
Thanks

**Comment by MariaNattestad** [comment]
I just checked. The server is not full, and I was able to upload a file
myself. Please try again.

**Comment by Gon1976** [comment]
I change my .delta file and start working and this error appear:

Starting unique anchor filtering.

Step 1: Assemblytics_uniq_anchor.py failed: Possible problem with Python or Python packages on server.

The .delta file with "no upload" message it's a self-self comparison. My nucmer command was: nucmer --maxmatch -l 100 -c 500 H1.fasta H1.fasta  -p H1vsH1

**Comment by MariaNattestad** [comment]
Just edit the first lines of the .delta file to give them different file
names. The two filenames are assumed to be different in the code.

**Comment by Gon1976** [comment]
Ok, the upload error continue changing the filenames. In the second case, i can upload the delta file (it different comparison) and I have another error:
Starting unique anchor filtering.

Step 1: Assemblytics_uniq_anchor.py failed: Possible problem with Python or Python packages on server.

I add my two delta files
[deltafiles.zip](https://github.com/MariaNattestad/Assemblytics/files/14605177/deltafiles.zip)

**Comment by MariaNattestad** [comment]
Okay I looked at your delta files, and they have weird formatting.

<img width="1672" alt="Screenshot 2024-03-14 at 10 22 31 AM" src="https://github.com/MariaNattestad/Assemblytics/assets/7958077/0434bde0-983d-4165-a03b-e28616c8d882">
<img width="1672" alt="Screenshot 2024-03-14 at 10 22 24 AM" src="https://github.com/MariaNattestad/Assemblytics/assets/7958077/0b2d4b28-17b4-4a2e-926e-0a345a1dfa88">

See line 3-4 and again in other places in the file:
<img width="717" alt="Screenshot 2024-03-14 at 10 23 33 AM" src="https://github.com/MariaNattestad/Assemblytics/assets/7958077/5fd1161a-c892-47b3-ba29-7d20724a88ab">

See a sample delta file here: http://assemblytics.com/sample.delta

I'm guessing you tried to change the file programmatically and accidentally added some newlines where they shouldn't be. When you fix this, please take a close look at your file in a text editor and also try running it through the MUMmer tool suite first before reporting problems in Assemblytics, since it will be faster for you to check that these files are valid using e.g. MUMmer's "show-aligns" or "coords" commands. Once those are working and it looks okay , then you can try Assemblytics again. Good luck!

**Comment by MariaNattestad** [comment]
Sorry this issue is totally different, we should have opened a new issue to deal with your problems @Gon1976. Please opena new issue now instead of replying here and just link to the comments above if you need to.

**Comment by brcliver** [comment]
Hi there, any chance the server is full?

**Comment by MariaNattestad** [comment]
Thanks, yes it was. Fixed!
Also I made a cron job that should hopefully prevent this from happening
again...we'll see if it works this time.
