### ISSUE TITLE
Error Running Assemblytics_within_alignment.py

### ISSUE THREAD

**Issue by jiaanqiang** [MariaNattestad/Assemblytics#56]
Hi Maria,
Thank you for creating such a useful tool. I've been running it successfully for most samples, 
but some are giving me the following error:

Traceback (most recent call last):
  File "Assemblytics_within_alignment.py", line 101, in <module>
    main()
  File "Assemblytics_within_alignment.py", line 98, in main
    args.func(args)
  File "Assemblytics_within_alignment.py", line 56, in run
    report = variants[-1]
IndexError: list index out of range

I'm not sure what's causing it. Any ideas on how to fix this?

Waiting for your reply.
Thanks

Jia

**Comment by MariaNattestad** [comment]
Sorry that's a bug. It should probably have been caught more gracefully. It looks like something that shouldn't happen given the delta file format, at least as far as I knew when I was coding Assemblytics, since there was no spec, so I was working it out based on example files. The bug you encountered doesn't appear to have ever popped up before in 8 years of usage, which is very odd. I'm curious what you used to generate the delta file that was input to Assemblytics.

**Comment by jiaanqiang** [comment]
Thank you for your response. The issue has been resolved.
